### ISSUE TITLE
Face detection using HAAR Classifying in OpenCV-Python

### ISSUE THREAD

**Issue by Pranjalmishra30** [life-sync/Python#5]
Program to detect faces in images and videos (eg-Webcam) using HAAR classification technique. Using the OpenCV library in python.

@ion05 Can i work on this issue ?

**Comment by ion05** [comment]
Sure !

**Comment by Pranjalmishra30** [comment]
Yes will do the required. I will also try to contribute more OpenCV code :) :+1:
